version: '3.8'

services:
  guivcard2:
    image: tiritibambix/guivcard2:latest
    container_name: guivcard2
    ports:
      - "8080:3000"
    restart: unless-stopped
    environment:
      - VUE_APP_RADICALE_URL=https://radicale.domain.com
      - VUE_APP_RADICALE_PATH=/username/contacts
      - VUE_APP_DEFAULT_USERNAME=username
      - VUE_APP_DEFAULT_PASSWORD=password
    networks:
      - default

networks:
  default:
    driver: bridge