version: '3.8'

services:
  guivcard2:
    image: tiritibambix/guivcard2:latest
    container_name: guivcard2
    ports:
      - "8080:3000"
    restart: unless-stopped
    environment:
      - VUE_APP_RADICALE_URL=http://localhost:5232
    networks:
      - default

networks:
  default:
    driver: bridge