version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VUE_APP_RADICALE_URL=https://radicale.domain.com
    restart: unless-stopped