version: '3.8'

services:
  guivcard2:
    image: tiritibambix/guivcard2:latest
    container_name: guivcard2
    ports:
      - "8080:3000"
    restart: unless-stopped
    networks:
      - guivcard_network

networks:
  guivcard_network:
    driver: bridge